// Curated list of major business hubs around the world, mapped to their
// IANA time zone identifiers. This powers the "add city" search. Any valid
// IANA zone can still be added manually as a fallback (see timezone.js).
const CITIES = [
  // North America
  { city: 'New York', country: 'United States', tz: 'America/New_York' },
  { city: 'Los Angeles', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'Chicago', country: 'United States', tz: 'America/Chicago' },
  { city: 'Denver', country: 'United States', tz: 'America/Denver' },
  { city: 'Phoenix', country: 'United States', tz: 'America/Phoenix' },
  { city: 'San Francisco', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'Seattle', country: 'United States', tz: 'America/Los_Angeles' },
  { city: 'Miami', country: 'United States', tz: 'America/New_York' },
  { city: 'Boston', country: 'United States', tz: 'America/New_York' },
  { city: 'Dallas', country: 'United States', tz: 'America/Chicago' },
  { city: 'Houston', country: 'United States', tz: 'America/Chicago' },
  { city: 'Honolulu', country: 'United States', tz: 'Pacific/Honolulu' },
  { city: 'Anchorage', country: 'United States', tz: 'America/Anchorage' },
  { city: 'Toronto', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Vancouver', country: 'Canada', tz: 'America/Vancouver' },
  { city: 'Montreal', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Calgary', country: 'Canada', tz: 'America/Edmonton' },
  { city: 'Ottawa', country: 'Canada', tz: 'America/Toronto' },
  { city: 'Mexico City', country: 'Mexico', tz: 'America/Mexico_City' },
  { city: 'Monterrey', country: 'Mexico', tz: 'America/Monterrey' },

  // Central America & Caribbean
  { city: 'Panama City', country: 'Panama', tz: 'America/Panama' },
  { city: 'San Jose', country: 'Costa Rica', tz: 'America/Costa_Rica' },
  { city: 'Havana', country: 'Cuba', tz: 'America/Havana' },
  { city: 'Kingston', country: 'Jamaica', tz: 'America/Jamaica' },
  { city: 'Santo Domingo', country: 'Dominican Republic', tz: 'America/Santo_Domingo' },
  { city: 'San Juan', country: 'Puerto Rico', tz: 'America/Puerto_Rico' },

  // South America
  { city: 'Sao Paulo', country: 'Brazil', tz: 'America/Sao_Paulo' },
  { city: 'Rio de Janeiro', country: 'Brazil', tz: 'America/Sao_Paulo' },
  { city: 'Brasilia', country: 'Brazil', tz: 'America/Sao_Paulo' },
  { city: 'Buenos Aires', country: 'Argentina', tz: 'America/Argentina/Buenos_Aires' },
  { city: 'Santiago', country: 'Chile', tz: 'America/Santiago' },
  { city: 'Lima', country: 'Peru', tz: 'America/Lima' },
  { city: 'Bogota', country: 'Colombia', tz: 'America/Bogota' },
  { city: 'Caracas', country: 'Venezuela', tz: 'America/Caracas' },
  { city: 'Quito', country: 'Ecuador', tz: 'America/Guayaquil' },
  { city: 'Montevideo', country: 'Uruguay', tz: 'America/Montevideo' },
  { city: 'La Paz', country: 'Bolivia', tz: 'America/La_Paz' },
  { city: 'Asuncion', country: 'Paraguay', tz: 'America/Asuncion' },

  // Western Europe
  { city: 'London', country: 'United Kingdom', tz: 'Europe/London' },
  { city: 'Manchester', country: 'United Kingdom', tz: 'Europe/London' },
  { city: 'Edinburgh', country: 'United Kingdom', tz: 'Europe/London' },
  { city: 'Dublin', country: 'Ireland', tz: 'Europe/Dublin' },
  { city: 'Paris', country: 'France', tz: 'Europe/Paris' },
  { city: 'Marseille', country: 'France', tz: 'Europe/Paris' },
  { city: 'Berlin', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Frankfurt', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Munich', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Hamburg', country: 'Germany', tz: 'Europe/Berlin' },
  { city: 'Madrid', country: 'Spain', tz: 'Europe/Madrid' },
  { city: 'Barcelona', country: 'Spain', tz: 'Europe/Madrid' },
  { city: 'Lisbon', country: 'Portugal', tz: 'Europe/Lisbon' },
  { city: 'Rome', country: 'Italy', tz: 'Europe/Rome' },
  { city: 'Milan', country: 'Italy', tz: 'Europe/Rome' },
  { city: 'Amsterdam', country: 'Netherlands', tz: 'Europe/Amsterdam' },
  { city: 'Rotterdam', country: 'Netherlands', tz: 'Europe/Amsterdam' },
  { city: 'Brussels', country: 'Belgium', tz: 'Europe/Brussels' },
  { city: 'Zurich', country: 'Switzerland', tz: 'Europe/Zurich' },
  { city: 'Geneva', country: 'Switzerland', tz: 'Europe/Zurich' },
  { city: 'Vienna', country: 'Austria', tz: 'Europe/Vienna' },
  { city: 'Luxembourg', country: 'Luxembourg', tz: 'Europe/Luxembourg' },

  // Nordics
  { city: 'Stockholm', country: 'Sweden', tz: 'Europe/Stockholm' },
  { city: 'Oslo', country: 'Norway', tz: 'Europe/Oslo' },
  { city: 'Copenhagen', country: 'Denmark', tz: 'Europe/Copenhagen' },
  { city: 'Helsinki', country: 'Finland', tz: 'Europe/Helsinki' },
  { city: 'Reykjavik', country: 'Iceland', tz: 'Atlantic/Reykjavik' },

  // Eastern Europe
  { city: 'Warsaw', country: 'Poland', tz: 'Europe/Warsaw' },
  { city: 'Prague', country: 'Czechia', tz: 'Europe/Prague' },
  { city: 'Budapest', country: 'Hungary', tz: 'Europe/Budapest' },
  { city: 'Bucharest', country: 'Romania', tz: 'Europe/Bucharest' },
  { city: 'Sofia', country: 'Bulgaria', tz: 'Europe/Sofia' },
  { city: 'Athens', country: 'Greece', tz: 'Europe/Athens' },
  { city: 'Kyiv', country: 'Ukraine', tz: 'Europe/Kyiv' },
  { city: 'Moscow', country: 'Russia', tz: 'Europe/Moscow' },
  { city: 'Istanbul', country: 'Turkey', tz: 'Europe/Istanbul' },

  // Africa
  { city: 'Cairo', country: 'Egypt', tz: 'Africa/Cairo' },
  { city: 'Lagos', country: 'Nigeria', tz: 'Africa/Lagos' },
  { city: 'Nairobi', country: 'Kenya', tz: 'Africa/Nairobi' },
  { city: 'Johannesburg', country: 'South Africa', tz: 'Africa/Johannesburg' },
  { city: 'Cape Town', country: 'South Africa', tz: 'Africa/Johannesburg' },
  { city: 'Casablanca', country: 'Morocco', tz: 'Africa/Casablanca' },
  { city: 'Accra', country: 'Ghana', tz: 'Africa/Accra' },
  { city: 'Addis Ababa', country: 'Ethiopia', tz: 'Africa/Addis_Ababa' },
  { city: 'Tunis', country: 'Tunisia', tz: 'Africa/Tunis' },
  { city: 'Algiers', country: 'Algeria', tz: 'Africa/Algiers' },
  { city: 'Dar es Salaam', country: 'Tanzania', tz: 'Africa/Dar_es_Salaam' },
  { city: 'Kampala', country: 'Uganda', tz: 'Africa/Kampala' },

  // Middle East
  { city: 'Dubai', country: 'United Arab Emirates', tz: 'Asia/Dubai' },
  { city: 'Abu Dhabi', country: 'United Arab Emirates', tz: 'Asia/Dubai' },
  { city: 'Doha', country: 'Qatar', tz: 'Asia/Qatar' },
  { city: 'Riyadh', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Jeddah', country: 'Saudi Arabia', tz: 'Asia/Riyadh' },
  { city: 'Kuwait City', country: 'Kuwait', tz: 'Asia/Kuwait' },
  { city: 'Manama', country: 'Bahrain', tz: 'Asia/Bahrain' },
  { city: 'Muscat', country: 'Oman', tz: 'Asia/Muscat' },
  { city: 'Tel Aviv', country: 'Israel', tz: 'Asia/Jerusalem' },
  { city: 'Jerusalem', country: 'Israel', tz: 'Asia/Jerusalem' },
  { city: 'Amman', country: 'Jordan', tz: 'Asia/Amman' },
  { city: 'Beirut', country: 'Lebanon', tz: 'Asia/Beirut' },
  { city: 'Baghdad', country: 'Iraq', tz: 'Asia/Baghdad' },
  { city: 'Tehran', country: 'Iran', tz: 'Asia/Tehran' },

  // South Asia
  { city: 'Mumbai', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Delhi', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Bengaluru', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Hyderabad', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Chennai', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Pune', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Kolkata', country: 'India', tz: 'Asia/Kolkata' },
  { city: 'Karachi', country: 'Pakistan', tz: 'Asia/Karachi' },
  { city: 'Lahore', country: 'Pakistan', tz: 'Asia/Karachi' },
  { city: 'Islamabad', country: 'Pakistan', tz: 'Asia/Karachi' },
  { city: 'Dhaka', country: 'Bangladesh', tz: 'Asia/Dhaka' },
  { city: 'Colombo', country: 'Sri Lanka', tz: 'Asia/Colombo' },
  { city: 'Kathmandu', country: 'Nepal', tz: 'Asia/Kathmandu' },

  // East / Southeast Asia
  { city: 'Singapore', country: 'Singapore', tz: 'Asia/Singapore' },
  { city: 'Hong Kong', country: 'Hong Kong SAR', tz: 'Asia/Hong_Kong' },
  { city: 'Shanghai', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Beijing', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Shenzhen', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Guangzhou', country: 'China', tz: 'Asia/Shanghai' },
  { city: 'Taipei', country: 'Taiwan', tz: 'Asia/Taipei' },
  { city: 'Tokyo', country: 'Japan', tz: 'Asia/Tokyo' },
  { city: 'Osaka', country: 'Japan', tz: 'Asia/Tokyo' },
  { city: 'Seoul', country: 'South Korea', tz: 'Asia/Seoul' },
  { city: 'Bangkok', country: 'Thailand', tz: 'Asia/Bangkok' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', tz: 'Asia/Ho_Chi_Minh' },
  { city: 'Hanoi', country: 'Vietnam', tz: 'Asia/Ho_Chi_Minh' },
  { city: 'Manila', country: 'Philippines', tz: 'Asia/Manila' },
  { city: 'Jakarta', country: 'Indonesia', tz: 'Asia/Jakarta' },
  { city: 'Kuala Lumpur', country: 'Malaysia', tz: 'Asia/Kuala_Lumpur' },
  { city: 'Yangon', country: 'Myanmar', tz: 'Asia/Yangon' },
  { city: 'Phnom Penh', country: 'Cambodia', tz: 'Asia/Phnom_Penh' },

  // Oceania
  { city: 'Sydney', country: 'Australia', tz: 'Australia/Sydney' },
  { city: 'Melbourne', country: 'Australia', tz: 'Australia/Melbourne' },
  { city: 'Brisbane', country: 'Australia', tz: 'Australia/Brisbane' },
  { city: 'Perth', country: 'Australia', tz: 'Australia/Perth' },
  { city: 'Adelaide', country: 'Australia', tz: 'Australia/Adelaide' },
  { city: 'Canberra', country: 'Australia', tz: 'Australia/Sydney' },
  { city: 'Auckland', country: 'New Zealand', tz: 'Pacific/Auckland' },
  { city: 'Wellington', country: 'New Zealand', tz: 'Pacific/Auckland' },
  { city: 'Fiji', country: 'Fiji', tz: 'Pacific/Fiji' },
  { city: 'Honolulu', country: 'United States', tz: 'Pacific/Honolulu' },

  // UTC reference
  { city: 'Coordinated Universal Time', country: 'UTC', tz: 'UTC' }
];

if (typeof module !== 'undefined') module.exports = CITIES;
